// File: ALUcontrol.v
// Generated by MyHDL 0.11
// Date: Thu Dec  2 18:05:32 2021


`timescale 1ns/10ps

module ALUcontrol (
    func3,
    func7,
    branchIn,
    controlOut
);


input [2:0] func3;
input [0:0] func7;
input [0:0] branchIn;
output [4:0] controlOut;
reg [4:0] controlOut;




always @(branchIn, func7, func3) begin: ALUCONTROL_CONTROL
    if ((branchIn == 1)) begin
        controlOut = {2, func3};
    end
    else begin
        controlOut = {0, func7, func3};
    end
end

endmodule
