// File: ControlUnit.v
// Generated by MyHDL 0.11
// Date: Thu Nov 18 01:33:49 2021


`timescale 1ns/10ps

module ControlUnit (
    opcode,
    R_type,
    I_type,
    B_type,
    L_type,
    S_type,
    U_type,
    UJ_type,
    Auipc_type,
    Jalr_type,
    branchOut,
    RegWriteOut,
    ImmediateOut,
    LoadOut,
    StoreOut,
    UtypeOut,
    AuipcOut,
    JalOut,
    JalrOut
);


input [6:0] opcode;
output [0:0] R_type;
reg [0:0] R_type;
output [0:0] I_type;
reg [0:0] I_type;
output [0:0] B_type;
reg [0:0] B_type;
output [0:0] L_type;
reg [0:0] L_type;
output [0:0] S_type;
reg [0:0] S_type;
output [0:0] U_type;
reg [0:0] U_type;
output [0:0] UJ_type;
reg [0:0] UJ_type;
output [0:0] Auipc_type;
reg [0:0] Auipc_type;
output [0:0] Jalr_type;
reg [0:0] Jalr_type;
output [0:0] branchOut;
reg [0:0] branchOut;
output [0:0] RegWriteOut;
reg [0:0] RegWriteOut;
output [0:0] ImmediateOut;
reg [0:0] ImmediateOut;
output [0:0] LoadOut;
reg [0:0] LoadOut;
output [0:0] StoreOut;
reg [0:0] StoreOut;
output [0:0] UtypeOut;
reg [0:0] UtypeOut;
output [0:0] AuipcOut;
reg [0:0] AuipcOut;
output [0:0] JalOut;
reg [0:0] JalOut;
output [0:0] JalrOut;
reg [0:0] JalrOut;




always @(opcode) begin: CONTROLUNIT_TYPEDECODE0_TYPEDEC
    R_type = 1'h0;
    I_type = 1'h0;
    B_type = 1'h0;
    L_type = 1'h0;
    S_type = 1'h0;
    U_type = 1'h0;
    UJ_type = 1'h0;
    Auipc_type = 1'h0;
    Jalr_type = 1'h0;
    case (opcode)
        'h33: begin
            R_type = 1'h1;
        end
        'h13: begin
            I_type = 1'h1;
        end
        'h63: begin
            B_type = 1'h1;
        end
        'h3: begin
            L_type = 1'h1;
        end
        'h23: begin
            S_type = 1'h1;
        end
        'h37: begin
            U_type = 1'h1;
        end
        'h6f: begin
            UJ_type = 1'h1;
        end
        'h17: begin
            Auipc_type = 1'h1;
        end
        'h67: begin
            Jalr_type = 1'h1;
        end
    endcase
end


always @(UJ_type, L_type, R_type, S_type, Jalr_type, Auipc_type, I_type, B_type, U_type) begin: CONTROLUNIT_CONTROLDECODE0_CONTROLDECODING
    branchOut = 1'h0;
    RegWriteOut = 1'h0;
    ImmediateOut = 1'h0;
    LoadOut = 1'h0;
    StoreOut = 1'h0;
    UtypeOut = 1'h0;
    AuipcOut = 1'h0;
    JalOut = 1'h0;
    JalrOut = 1'h0;
    if ((B_type == 1'h1)) begin
        branchOut = 1'h1;
    end
    if (((((((UJ_type | U_type) | R_type) | I_type) | L_type) | Auipc_type) == 1'h1)) begin
        RegWriteOut = 1'h1;
    end
    if ((((I_type | S_type) | L_type) == 1'h1)) begin
        ImmediateOut = 1'h1;
    end
    if ((S_type == 1'h1)) begin
        StoreOut = 1'h1;
    end
    if ((L_type == 1'h1)) begin
        LoadOut = 1'h1;
    end
    if ((U_type == 1'h1)) begin
        UtypeOut = 1'h1;
    end
    if ((Auipc_type == 1'h1)) begin
        AuipcOut = 1'h1;
    end
    if ((Jalr_type == 1'h1)) begin
        JalrOut = 1'h1;
    end
    if ((UJ_type == 1'h1)) begin
        JalOut = 1'h1;
    end
end

endmodule
