// File: PC.v
// Generated by MyHDL 0.11
// Date: Sat Dec  4 23:15:41 2021


`timescale 1ns/10ps

module PC (
    clk,
    input,
    pc,
    pc4
);


input clk;
input [31:0] input;
output [31:0] pc;
wire [31:0] pc;
output [31:0] pc4;
wire [31:0] pc4;

reg [31:0] reg;



always @(input, clk) begin: PC_WRITE
    if ((clk == 1)) begin
        reg = input;
    end
end



assign pc = reg;
assign pc4 = (reg + 4);

endmodule
